name: tpo lab2

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up jdk21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'gradle'
          distribution: 'temurin'

      - name: setup gradlew
        uses: gradle/actions/setup-gradlew@v3

      - name: build and run tests
        run: ./gradlew clean build test jacocoTestReport --stacktrace

      - name: upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/reports/jacoco
          retention-days: 5

      - name: deploy coverage
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/jacoco/test/html